# Generated by Django 5.0 on 2024-04-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_amount_directionoftraining_institute_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='supervisorOPOP',
        ),
    ]
