# Generated by Django 5.0 on 2024-04-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_practice_supervisoropop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='direction_of_training',
        ),
        migrations.AlterField(
            model_name='practice',
            name='title_place',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='group',
            name='direction_of_training',
            field=models.ManyToManyField(to='user.directionoftraining'),
        ),
    ]
