# Generated by Django 5.0 on 2024-04-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_group_direction_of_training_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directionoftraining',
            name='supervisorOPOP',
        ),
        migrations.AddField(
            model_name='directionoftraining',
            name='supervisorOPOP',
            field=models.ManyToManyField(to='user.supervisoropop'),
        ),
    ]
