# Generated by Django 5.0 on 2024-05-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_directionoftraining_supervisoropop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicestudent',
            name='hard_quality',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='practicestudent',
            name='remark',
            field=models.TextField(),
        ),
    ]
