# Generated by Django 5.0 on 2024-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_practicestudent_hard_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicestudent',
            name='quality',
            field=models.TextField(),
        ),
    ]
