# Generated by Django 5.0 on 2024-05-01 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_practicestudent_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, unique=True)),
                ('date', models.DateField()),
                ('practiceStudent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.practicestudent')),
            ],
        ),
    ]
