# Generated by Django 5.0 on 2024-05-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_practicestudent_hard_quality_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionTasks',
        ),
    ]
