# Generated by Django 5.0 on 2024-05-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_delete_productiontasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='supervisor_practice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.supervisorpractice'),
        ),
    ]
