# Generated by Django 5.0 on 2024-05-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_practice_supervisor_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicestudent',
            name='practice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.practice'),
        ),
    ]
