# Generated by Django 5.0 on 2024-05-01 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_practicestudent_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='number_decree',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='practicestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
    ]
