# Generated by Django 5.0 on 2024-05-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_practice_fio_supervisor_yusu_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
