# Generated by Django 5.0 on 2024-05-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_delete_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicestudent',
            name='production_tasks',
            field=models.TextField(null=True),
        ),
    ]
