# Generated by Django 5.0 on 2024-05-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_group_direction_of_training_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='direction_of_training',
        ),
        migrations.AddField(
            model_name='group',
            name='direction_of_training',
            field=models.ManyToManyField(to='user.directionoftraining'),
        ),
    ]
