# Generated by Django 5.0 on 2024-05-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisoropop',
            name='post',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='supervisorpractice',
            name='post',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
