# Generated by Django 5.0 on 2024-05-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_supervisoropop_post_supervisorpractice_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicestudent',
            name='rating',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, null=True),
        ),
    ]
