# Generated by Django 5.0 on 2024-05-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_remove_group_direction_of_training_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='title',
        ),
    ]
