# Generated by Django 5.0 on 2024-05-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_rename_number_group_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='kind',
            field=models.CharField(choices=[('kind1', 'учебная'), ('kind2', 'производственная')], max_length=20),
        ),
        migrations.AlterField(
            model_name='practice',
            name='type',
            field=models.CharField(choices=[('type1', 'преддипломная'), ('type2', 'ознакомительная'), ('type2', 'технологическая'), ('type2', 'производственна'), ('type2', 'научно-исследовательская')], max_length=20),
        ),
        migrations.AlterField(
            model_name='practicestudent',
            name='type',
            field=models.CharField(choices=[('long_term', 'долгосрочный'), ('краткосрочный', 'краткосрочный')], max_length=20),
        ),
    ]
