# Generated by Django 5.0 on 2024-05-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_practice_kind_alter_practice_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicestudent',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='practicestudent',
            name='hard_quality',
        ),
        migrations.RemoveField(
            model_name='practicestudent',
            name='pay',
        ),
        migrations.RemoveField(
            model_name='practicestudent',
            name='production_tasks',
        ),
        migrations.RemoveField(
            model_name='practicestudent',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='practicestudent',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='practicestudent',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='practicestudent',
            name='type',
        ),
        migrations.CreateModel(
            name='RatingPracticeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('long_term', 'долгосрочный'), ('краткосрочный', 'краткосрочный')], max_length=20)),
                ('pay', models.BooleanField()),
                ('production_tasks', models.TextField(null=True)),
                ('hard_quality', models.TextField(null=True)),
                ('quality', models.TextField(null=True)),
                ('remark', models.TextField(null=True)),
                ('rating', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, null=True)),
                ('amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.amount')),
                ('practice_student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.practicestudent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProductionTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, unique=True)),
                ('data', models.DateField()),
                ('practice_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.practicestudent')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorPracticeProductionTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.TextField(null=True)),
                ('practice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.practice')),
            ],
        ),
    ]
