# Generated by Django 5.0 on 2024-05-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_remove_practicestudent_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproductiontasks',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentproductiontasks',
            name='title',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
