# Generated by Django 5.0 on 2024-05-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_directionoftraining_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='form_of_education',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='group_gid',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='specialty_code',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='specialty_name',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
