# Generated by Django 5.0 on 2024-05-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_group_form_of_education_group_group_gid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='form_of_education',
            field=models.CharField(choices=[('full-time', 'очная'), ('part-time', 'очно-заочная'), ('extramural', 'заочная')], max_length=512, null=True),
        ),
    ]
