# Generated by Django 5.0 on 2024-05-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_alter_group_form_of_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('no', 'нет'), ('part-time', 'декретный отпуск'), ('extramural', 'академический отпуск')], max_length=512, null=True),
        ),
    ]
