# Generated by Django 5.0 on 2024-05-04 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_student_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionoftraining',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.institute'),
        ),
        migrations.AlterField(
            model_name='directionoftraining',
            name='supervisorOPOP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.supervisoropop'),
        ),
        migrations.AlterField(
            model_name='directionoftraining',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='group',
            name='direction_of_training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.directionoftraining'),
        ),
        migrations.AlterField(
            model_name='group',
            name='form_of_education',
            field=models.CharField(choices=[('full-time', 'очная'), ('part-time', 'очно-заочная'), ('extramural', 'заочная')], max_length=512),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_gid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='group',
            name='specialty_code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='group',
            name='specialty_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='practice',
            name='adress_place',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='practice',
            name='fio_supervisor_YuSU',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='practice',
            name='post_supervisor_YuSU',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='practice',
            name='title_place',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='practicestudent',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.practice'),
        ),
        migrations.AlterField(
            model_name='ratingpracticestudent',
            name='hard_quality',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ratingpracticestudent',
            name='practice_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.practicestudent'),
        ),
        migrations.AlterField(
            model_name='ratingpracticestudent',
            name='production_tasks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ratingpracticestudent',
            name='quality',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ratingpracticestudent',
            name='rating',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingpracticestudent',
            name='remark',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reportgroup',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentproductiontasks',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentproductiontasks',
            name='practice_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.practicestudent'),
        ),
        migrations.AlterField(
            model_name='studentproductiontasks',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='supervisoropop',
            name='post',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='supervisorpractice',
            name='post',
            field=models.CharField(max_length=256),
        ),
    ]
