# Generated by Django 5.0 on 2024-05-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_alter_directionoftraining_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='type',
            field=models.CharField(choices=[('type1', 'преддипломная'), ('type2', 'ознакомительная'), ('type3', 'технологическая'), ('type4', 'производственна'), ('type5', 'научно-исследовательская')], max_length=20),
        ),
    ]
