# Generated by Django 5.0 on 2024-05-04 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_alter_practice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.group'),
        ),
        migrations.AlterField(
            model_name='reportgroup',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.practice'),
        ),
    ]
