# Generated by Django 5.0 on 2024-04-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionOfTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('level', models.CharField(choices=[('Bachelor', 'Бакалавриат'), ('Specialist', 'Специалитет'), ('Master', 'Магистратура'), ('PhD', 'Аспирантура')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('direction_of_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.directionoftraining')),
            ],
        ),
        migrations.AddField(
            model_name='directionoftraining',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.institute'),
        ),
    ]
