# Generated by Django 5.0 on 2024-04-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_amount_practicestudent'),
        ('supervisorOPOP', '0002_place_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicestudent',
            name='practice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supervisorOPOP.practice'),
        ),
    ]
