# Generated by Django 5.0 on 2024-04-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_practicestudent_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicestudent',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='directionoftraining',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='directionoftraining',
            name='supervisorOPOP',
        ),
        migrations.RemoveField(
            model_name='group',
            name='direction_of_training',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='practicestudent',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='practicestudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
        migrations.DeleteModel(
            name='DirectionOfTraining',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='PracticeStudent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
