# Generated by Django 5.0 on 2024-04-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisorPractice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupervisorPractice',
        ),
    ]
