# Generated by Django 5.0 on 2024-04-30 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisorOPOP', '0002_place_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='place',
        ),
        migrations.AddField(
            model_name='practice',
            name='adress_place',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='practice',
            name='supervisorOPOP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervisorOPOP.supervisoropop'),
        ),
        migrations.AddField(
            model_name='practice',
            name='title_place',
            field=models.CharField(default=None, max_length=512, unique=True),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
