# Generated by Django 5.0 on 2024-04-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_practicestudent_amount_and_more'),
        ('supervisorOPOP', '0003_remove_practice_place_practice_adress_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisoropop',
            name='user',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.DeleteModel(
            name='SupervisorOPOP',
        ),
    ]
